baseURL: "https://www.crashdive.co.uk/"
title: "Crash Dive"
languageCode: "en-GB"
disableKinds: ["taxonomy", "RSS"]
enableRobotsTXT: true
disableHugoGeneratorInject: true
sitemap:
    changefreq: monthly
